### ISSUE TITLE
Build Tool Choice

### ISSUE THREAD

**Issue by jundl77** [TruffleHog/TruffleHog#1]
Wir sollten ein build tool aussuchen für unser Java Projekt:
Maven?
Gradle?

Ich werde noch eine Beschreibung beider tools später hinzufügen, wenn ihr andere Vorschläge habt, einfach hinzufügen!

**Comment by mlgiraud** [comment]
Ich würde sagen Maven. Das haben wir (hoffentlich) alle schon mal in SWT I benutzt. Da kennt sich jeder schon etwas mit aus denke ich.

**Comment by JanSurft** [comment]
Vote: Maven

**Comment by jundl77** [comment]
Also bevor wir das entscheiden sollten wir uns erstmal beide build tools genauer ansehen. Ich finde Gradle hat erhebliche Vorteile. 

Maven kam in 2004 raus und ist XML basiert was für große Projekte schnell unübersichtlich wird. Gradle kam in 2012 raus, ist also viel moderner und versucht "the best of both worlds" von Maven und einem noch älterem build tool Ant zu nehmen und zu kombinieren. Ant ist flexible und Gradle versucht diese Flexibilität mit Mavens Simplizität zu vereinen. Allerdings verwandeln sich Maven und Ant bei größeren Projekten schnell zu sehr viel Code der nicht sehr viel erreicht und unübersichtlich wird. 

Gradle benutzt kein XML sondern eine Sprache namens Groovy, also wird das ganze viel kompakter und übersichtlicher.

Zum Beispiel ist Google gleich am Anfang als Gradle raus kam auf Gradle gewechselt für Android. 

Obwohl wir jetzt mit Maven etwas Erfahrung haben, ist es besser denke ich wenn wir das modernere build tool nehmen, selbst wenn wir es noch nicht kennen. Erstens kriegen wir Erfahrung dammit was doch schon mal auch nicht schlecht ist, dann haben wir beides gesehen, und können dann in der Zukunft besser entscheiden was denn nun wirklich besser ist. Außerdem sollten wir nicht anfangen bei so einem Projekt ein älteres build tool zu nehmen. Schließlich soll es ja wahrscheinlich auch noch weiterentwickelt werden, und dann ist das modernere angenehmer. 

Hier ist etwas Beispiel code der das selbe tut:

##### Maven:

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
    http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.technologyconversations</groupId>
    <artifactId>java-build-tools</artifactId>
    <packaging>jar</packaging>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
        </dependency>
    </dependencies>

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>2.12.1</version>
        <executions>
            <execution>
                <configuration>
                    <configLocation>config/checkstyle/checkstyle.xml</configLocation>
                    <consoleOutput>true</consoleOutput>
                    <failsOnError>true</failsOnError>
                </configuration>
                <goals>
                    <goal>check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>2.5.4</version>
        <executions>
            <execution>
                <goals>
                    <goal>check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <version>3.1</version>
        <executions>
            <execution>
                <goals>
                    <goal>check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
            </plugin>
        </plugins>
    </build>
</project>
```

##### Und jetzt das selbe in Gradle:

``` groovy
apply plugin: 'java'
apply plugin: 'checkstyle'
apply plugin: 'findbugs'
apply plugin: 'pmd'

version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
}
```

Also Gradle ist ne ganze menge simpler

##### Kann nur Gradle:
- Dynamic Dependencies: Resolved dependency versions can be dynamic. Gradle supports the Maven snapshot mechanism but is more powerful than that. You can declare a dependency on the latest release, most current development version, or even the latest 4.x build.
- **Build C/C++/Obj-C/Obj-C++/Assembler: Gradle has built in support for compiling and linking programs using Assembler, C/C++ and Obj-C/C++. Gradle can build shared and static libraries and executables (interesting for spp_profinet which is in c).**
- **CUnit Test Support: Gradle supports testing C applications with CUnit (again, interesting for spp_profinet which is in c)** 
- Build automatically when sources change
- Version agnostic: The Gradle tooling API is back and forward compatible. With a particular version of the Tooling API you can drive build across all Gradle version since 1.0.
- Provide Eclipse Project Model: The Gradle Tooling API provides a model of how your project is mapped to an Eclipse project.
- Provide IDEA Project Model: The Gradle Tooling API provides a model how to your project is mapped to the IDEA model.
- Embedded GUI: In addition to supporting a traditional command line interface and IDE integration, Gradle offers a graphical user interface. This is a stand alone user interface that can be launched with the --gui option.

[Hier](http://gradle.org/maven_vs_gradle/) ist eine ganze menge mehr.

Sonst noch mehr infos: 
http://technologyconversations.com/2014/06/18/build-tools/

Außerdem wenn man mal googelt "maven vs Gradle" sagen alle Gradle haha :P

Aber gut ich bin dafür das wir was neues lernen und Gradle ausprobieren, sieht eine ganze menge einfacher aus.

**Comment by mlgiraud** [comment]
Für C wird Gradle irrelevant sein, da wir da höchstwahrscheinlich die Makefiles von Snort verwenden werden.
