### ISSUE TITLE
Implementierungsfortschritt

### ISSUE THREAD

**Issue by jundl77** [TruffleHog/TruffleHog#18]
##### Implementierte Komponenten (d.h. sie sind getestet und in der master branch):
- FileSystem
- command queue package
- executor (evtl. noch änderungen zum starten stoppen?)
- util
##### Komponenten in Bearbeitung:
- replaylogging
- command package
- packetdataprocessor package
- view

**Comment by Gynjd** [comment]
##### Vorläufige Aufteilung der Packages:

Jan (+ bei Bedarf ein Freiwilliger):
- spp_profinet

Julian:
- service/replaylogging
- model/configdata
- model/filter

Mark:
- command/queue (fertig?)
- service/packetdataprocessor
- service/executor (fertig?)

Max:
- view
- GUI part vom presenter

Valentin:
- command/trufflecommand
- command/usercommand

Dimitri:
- model/graph
- model/truffledatalog

Verblieben sind:
- interaction
- presenter (zum Schluss)
