### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by mlgiraud** [TruffleHog/TruffleHog#2]
Ich schlage ja vor, IntelliJ IDEA zu benutzen, falls ihr das nicht sowieso schon tut.
https://www.jetbrains.com/idea/

Die IDE hat alles was man so braucht (glaube ich :D) und kostet (für Studenten) nichts.

_(Scheiß auf Eclipse)_

**Comment by jundl77** [comment]
Nee ich kann nur zustimmen, ich benutze IntelliJ schon seit einem Jahr jetzt, und es ist echt super, es gibt ne ganze Menge handy tricks. Wenn ihr wollt kann ich euch die mal Zeigen

Ich bin für ein starkes Plus
