### ISSUE TITLE
Presenter singleton somewhat strange

### ISSUE THREAD

**Issue by Sofoca** [TruffleHog/TruffleHog#28]
Das singleton pattern beim Presenter finde ich komisch. Ist das so gedacht, das man sich **ein mal** einen erstellen kann und, dass beim zweiten Versuch eine Exception geworfen wird? 

https://github.com/TruffleHog/TruffleHog/blob/master/src/main/java/edu/kit/trufflehog/presenter/Presenter.java

**Comment by mlgiraud** [comment]
Neine, finde ich nicht sinnvoll. Mach lieber einen richtigen Singleton daraus.
Siehe auch https://github.com/TruffleHog/TruffleHog/commit/f84bf003368218c1e5e54d3f91e7dcd52a3b1661

**Comment by Sofoca** [comment]
Falls niemand bis morgen noch Einwände einlegt mache ich das so.

**Comment by jundl77** [comment]
Nee änder es so - das war ich am anfang, hab da irgendetwas hingeklatscht :P
