### ISSUE TITLE
GUI-Design vote

### ISSUE THREAD

**Issue by Sofoca** [TruffleHog/TruffleHog#38]
Es stellt sich gerade folgende Grundsatzentscheidung: 

Sollen wir Standarddesign (zum Beispiel das Einstellungsfenster) beibehalten oder manches selbst designen. Ich bin der Meinung, dass JavaFX 8 Mondena auf allen Plattformen in Ordnung aussieht und man sich an die Designrichtlinien von Java halten sollte. Ich finde auch den Button nicht besonders schön, da könnte man noch mehr Richtung Standard gehen (zum Beispiel mit einem Kontextmenü stattdessen).  

Julian: 
Ich finde, dass in den meisten Fällen das standard Design hässlich ist. Z.b. wie gesagt fände ich es besser, wenn das settings Menu keine eigenes pop-up Fenster ist, sondern eine Art etwas transparentes Overlay bei dem Knopf.

Max: 
Ich möchte anmerken, dass die ganzen Elemente von JavaFX (Checkbox, Drop down, Textfeld) richti scheiße aussehen auf dunklem transparenten Hintergrund und, dass man das dann alles neu stylen muss.

**Comment by Sofoca** [comment]
+1

**Comment by Sofoca** [comment]
+1

**Comment by jundl77** [comment]
Also das ist nicht wahr, ich will keine "iPad-mäßiges" Design. Ich finde nur das in den meisten fällen das standard design sehr hässlich ist. Z.b. wie gesagt fände ich es besser, wenn das settings menu keine eigenes pop-up Fenster ist, sondern eine Art etwas transparentes overlay bei dem Knopf.

**Comment by Sofoca** [comment]
Ich möchte anmerken, dass die ganzen Elemente von JavaFX (Checkbox, Drop down, Textfeld) richti scheiße aussehen auf dunklem transparenten Hintergrund und, dass man das dann alles neu stylen muss.

**Comment by jundl77** [comment]
Es muss ja auch kein dunkler Hintergrund sein. Alles was ich sage, ist das das standard Fenster mist ist.

**Comment by Sofoca** [comment]
Wenn es im Main Window als transparentes Overlay ist wird es defintiv dunkel.

**Comment by mlgiraud** [comment]
Ich finde wir können uns darüber auch zu einem späteren Zeipunkt Gedanken machen. Das Design ist doch erstmal völlig irrelevant. Uns interessiert ja vorerst nur das Layout und die funktionalität.

Das Design kann man ja später immernoch leicht anpassen.

**Comment by jundl77** [comment]
Das Design ist, dass was andere sehen, und wenn es erstmal gemacht ist, wird keiner Lust haben alles nochmal zu ändern. Natürlich ist der Rest wichtig, aber das Design sollten wir nicht unter den Tisch kehren. Ich finde es ist genauso wichtig.
