### ISSUE TITLE
Statistikgraphen

### ISSUE THREAD

**Issue by Sofoca** [TruffleHog/TruffleHog#39]
Wir hatten mal angedacht, im Hautfenster Statistikgraphen anzuzeigen, zum Beispiel "packet count" auf der y- und Zeit auf der x-Achse. Hierfür müsste man sich potenziell noch eine Datenstruktur einfallen lassen, falls man solche "historischen" Daten verfügbar haben will.

**Comment by mlgiraud** [comment]
Du meinst eine art StatisticsLog, der dann jede sekunde oder so ein Paar speichert?: (Time, PacketCount)
