### ISSUE TITLE
fragen auf die ich antwort brauch

### ISSUE THREAD

**Issue by Valentin987** [TruffleHog/TruffleHog#53]
ich denk mit nem issue bekomm ich eher die antworten:
-NodeInfoComponent: ich bräucht da sowas wie ne boolean isLegal mit setter und getter, oder wollt ihr das mit setColor auf rot für illegal festlegen?
-updateFilterCommand: der soll ja auch die filter anwenden, dafür bräucht ich ne liste von allen knoten im graph. soll man so einen getter in den networkreadingPort einbauen? oder soll der command einfach nur neue filterInputs schreiben?
-IFilter: ich denk wenn man das fenster für die macht brauchen die auch einen Namen oder sonst irgendein ID
OverlayViewController für knotenstatistikfenster: soll das fenster für jeden knoten unsichtbar immer mitgeführt werden und bei anklicken einfach auf visible = true? oder werden die bei anklicken erst gefüllt?

**Comment by jundl77** [comment]
@Valentin987 Denk dir doch selber Sachen aus :D  (aber bitte nicht bei Filters, da bin ich grad dabei)
